# Generated by Django 3.0.6 on 2020-05-27 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('카페명', models.CharField(max_length=20)),
                ('전화번호', models.CharField(max_length=20)),
                ('주소', models.CharField(max_length=30)),
                ('영업시간', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('카테고리', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('문이름', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('이름', models.CharField(max_length=20)),
                ('가격', models.CharField(max_length=10)),
                ('카페', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeyo.Cafe')),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='문',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafeyo.Gate'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='카테고리',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafeyo.Category'),
        ),
    ]
