# Generated by Django 3.0.6 on 2020-06-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeyo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='영업시간',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='전화번호',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
